---
title: 'Titanic: Purrr and Caret'
author: "Bastien Haller"
output: 
  html_document:
    theme: cosmo
    highlight: monochrome
    toc: true
    toc_float: false
    toc_depth: 4
    number_sections: true
    code_folding: hide
    df_print: kable


---


#Libraries
```{r libraries,message=FALSE,warning=FALSE}
rm(list=ls())
setwd("C:/Users/Bastien/Desktop/Kurse/Kaggle/Titanic")
set.seed(1)
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(purrr)
library(caret)
library(caretEnsemble)
library(Metrics)
library(readr)
library(gridExtra)
library(knitr)
library(corrplot)
require(DiagrammeR)
library("mxnet")

train<-read_csv("train.csv")
test<-read_csv("test.csv")
train$dset<-"train"
test$dset<-"test"
test$Survived<-NA
combined<-bind_rows(train,test)

```


#Explanatory Data Analysis
```{r Explanatory,message=FALSE,warning=FALSE}


glimpse(train)
glimpse(test)

combined$Sex<-as.factor(combined$Sex)
combined$Pclass<-as.factor(combined$Pclass)
combined$PassengerId<-as.character(combined$PassengerId)


data.frame(NumberNA=map_dbl(combined[,c(-1,-2,-13)], function(x){sum(is.na(x))}))


p1<-combined%>%filter(dset=="train")%>%
  ggplot(aes(x=as.factor(Survived),fill=Sex))+geom_bar()+
   geom_text(stat="count",aes(label=..count..),position = "stack",vjust=1,size=4)+
  labs(x="Survived")+
  theme(legend.position="none")

p2<-combined%>%filter(dset=="train")%>%
  group_by(Sex)%>%
  summarise(SurvivalRate=mean(Survived))%>%
  ggplot(aes(x=Sex,y=SurvivalRate,fill=Sex))+geom_col()+
  geom_text(aes(label=round(SurvivalRate,2)))+expand_limits(y=1)

  
grid.arrange(p1,p2,nrow=1,top="Survival by Gender")
combined%>%filter(dset=="train")%>%group_by(Sex)%>%summarise(count=n(),SurivalRate=mean(Survived))


p3<-combined%>%
  filter(dset=="train")%>%
    ggplot(aes(x=Pclass,fill=Pclass))+geom_bar(stat="count",position="dodge")+
    geom_text(stat="count",aes(label=..count..))

p4<-combined%>%filter(dset=="train")%>%
  ggplot(aes(x=Pclass,fill=as.factor(Survived)))+geom_bar()+facet_wrap(~Sex)+theme(legend.position = "none")


p5<-combined%>%filter(dset=="train")%>%
  ggplot(aes(x=Pclass,fill=as.factor(Survived)))+geom_bar(position="fill")+facet_wrap(~Sex)+
  labs(fill="Survived",y="percent")

grid.arrange(p3,p4,p5,layout_matrix=rbind(c(1,1),c(2,3)),top="Survival by Class")


combined%>%filter(dset=="train")%>%group_by(Pclass,Sex)%>%summarise(count=n(),SurivalRate=mean(Survived))





```
# Feature Engineering
```{r Feature Engineering,message=FALSE,warning=FALSE}

combined<-combined%>%mutate(PClassSex=paste("P",Pclass,Sex,sep=""))

combined<-combined%>%mutate(FamilyName=substr(Name,1,str_locate(Name,",")-1),
                  title=substr(Name,str_locate(Name,",")+2,str_locate(Name,"\\.")-1)
                  )

p6<-combined%>%filter(dset=="train")%>%
  group_by(Sex,title)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  ggplot(aes(y=SurvivalRate,x=count,col=title))+geom_jitter()+facet_grid(~Sex)+scale_x_log10()+labs(x="# Pax")

combined%>%
  group_by(Sex,title)%>%
  summarise(count=n(),SurvivalRate=mean(Survived,na.rm=TRUE))%>%arrange(count,desc(SurvivalRate))

combined<-combined%>%mutate(title=ifelse(title %in% c("Mlle","Ms"),"Miss",title))
combined<-combined%>%mutate(title=ifelse(title %in% c("Mme"),"Mrs",title))
combined<-combined%>%mutate(title=ifelse(title %in% c("Jonkheer","Rev","Capt"),"Mr",title))
combined<-combined%>%
  mutate(title=ifelse(title %in% c("Dr","Lady","the Countess","Don","Dona","Sir","Major","Col"),"RareTitle",title))

p7<-combined%>%filter(dset=="train")%>%
  group_by(Sex,title)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  ggplot(aes(y=SurvivalRate,x=count,col=title))+geom_jitter()+facet_grid(~Sex)+scale_x_log10()+labs(x="# Pax")

grid.arrange(p6,p7,ncol=2,top="Survival by Title")

combined<-combined%>%mutate(fsize=SibSp+Parch+1)

p8<-combined%>%filter(dset=="train")%>%
  ggplot(aes(x=fsize,fill=as.factor(Survived)))+geom_bar(stat="count", position='dodge')+
  labs(fill="Survived")

p9<-combined%>%filter(dset=="train")%>%group_by(fsize)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  arrange(desc(SurvivalRate))%>%ggplot(aes(x=fsize,y=SurvivalRate,fill=factor(fsize)))+geom_col()+
  theme(legend.position = "none")+expand_limits(y=1)



grid.arrange(p8,p9,ncol=2,top="Survial by Family size")

combined%>%filter(dset=="train")%>%group_by(fsize)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  arrange(desc(SurvivalRate))


TicketGroup<-combined%>%group_by(Ticket)%>%summarise(Tsize=n())
combined<-combined%>%left_join(TicketGroup,by="Ticket")

combined%>%filter(dset=="train")%>%count(Embarked)


#replace NA by most common value
combined$Embarked[is.na(combined$Embarked)]<-"S"


combined<-combined%>%mutate(FarePP=Fare/Tsize)
#replace missing and 0 fares by respective median of Pclass and Embarked
medianFares<-combined%>%filter(dset=="train")%>%group_by(Pclass,Embarked)%>%
  summarise(medianFare=median(Fare,na.rm=TRUE),medianFarePP=median(FarePP,na.rm=TRUE))



combined<-combined%>%inner_join(medianFares,by=c("Pclass"="Pclass","Embarked"="Embarked"))


combined[is.na(combined$Fare),"Fare"]=combined[is.na(combined$Fare),"medianFare"]


combined[is.na(combined$FarePP)|combined$FarePP==0,"FarePP"]=combined[is.na(combined$FarePP)|combined$FarePP==0,"medianFarePP"]


plotHist=function(x,bins=30){
  
combined%>%filter(dset=="train")%>%ggplot(aes_string(x=x))+geom_histogram(bins=bins,fill="blue")  
  
}

plotCols<-list("Fare","FarePP")
bins=list(30,30)

p10<-map2(plotCols,bins,plotHist)

grid.arrange(p10[[1]],p10[[2]],ncol=2,top="Distribution of Fares")



p11<-combined%>%filter(dset=="train")%>%ggplot(aes(x=Age,fill=factor(Survived)))+geom_histogram()+facet_wrap(~Survived)+
  theme(legend.position = "none")



##replace missing Age values by rf predictions
mycontrol<-trainControl(method = "cv",number=5,verboseIter = FALSE)

ageorig<-combined%>%group_by(title)%>%
  summarise(NAP=sum(is.na(Age)),
            medianAge=median(Age,na.rm=TRUE),
            meanAgeOrig=mean(Age,na.rm=TRUE))

model_Age<-train(Age~Pclass+Sex+SibSp+Parch+Fare+Embarked+title+Tsize,
      data=combined[!is.na(combined$Age),],
      method="ranger",
      tuneGrid=expand.grid(.mtry=5,.splitrule="extratrees"),
      trControl=mycontrol)

combined[is.na(combined$Age),"Age"]<-predict(model_Age,combined[is.na(combined$Age),])

p12<-combined%>%filter(dset=="train")%>%ggplot(aes(x=Age,fill=factor(Survived)))+geom_histogram()+facet_wrap(~Survived)+
  theme(legend.position = "none")


ageest<-combined%>%group_by(title)%>%
  summarise(medianAgeEstimated=median(Age,na.rm=TRUE),
            meanAgeEstimated=mean(Age,na.rm=TRUE))


##compare orig and new estimation
grid.arrange(p11,p12,ncol=2,top="Original vs Estimated Age Distribution")

bind_cols(ageorig,ageest)%>%select(-title1)

combined<-combined%>%mutate(Ischild=ifelse(Age<15,"Yes","No"))



### 
TicketGroup<-combined%>%group_by(Ticket)%>%
  summarise(Tsize=n(),minAge=min(Age),NumNA=sum(is.na(Survived)),SumSurvived=sum(Survived,na.rm=TRUE))%>%ungroup()%>%
  mutate(HasChildren=ifelse(minAge<=15 & Tsize>1,"Yes","No"),
         KnownSurvivor=ifelse(SumSurvived>=1 & Tsize>1,"Yes","No"))
combined<-combined%>%select(-Tsize)%>%left_join(TicketGroup,by="Ticket")




p13<-combined%>%filter(dset=="train")%>%
  ggplot(aes(x=Tsize,fill=as.factor(Survived)))+geom_bar(stat="count", position='dodge')+
  labs(fill="Survived")

p14<-combined%>%filter(dset=="train")%>%group_by(Tsize)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  arrange(desc(SurvivalRate))%>%ggplot(aes(x=Tsize,y=SurvivalRate,fill=factor(Tsize)))+geom_col()+
  theme(legend.position = "none")+expand_limits(y=1)

grid.arrange(p13,p14,ncol=2,top="Survival by Ticketsize")


combined%>%filter(dset=="train")%>%group_by(Tsize)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  arrange(desc(SurvivalRate))

## creating factors for groups

combined$TsizeCat<-NA
combined$TsizeCat[combined$Tsize==1]<-"solo"
combined$TsizeCat[combined$Tsize==2]<-"couple"
combined$TsizeCat[combined$Tsize>2 & combined$Tsize<5]<-"group"
combined$TsizeCat[combined$Tsize>=5]<-"largeGroup"
combined$TsizeCat<-as.factor(combined$TsizeCat)

combined%>%filter(dset=="train")%>%group_by(TsizeCat)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  arrange(desc(SurvivalRate))


combined<-combined%>%mutate(FamilyID=ifelse(fsize>2,
                              paste(as.character(fsize),FamilyName,sep=""),
                              "small"))

fam<-combined%>%dplyr::count(FamilyID)%>%filter(n<=2)

combined$FamilyID[combined$FamilyID %in% fam$FamilyID]<-"small"


##replace NA with U and use first Letter for the Deck
combined$Cabin[is.na(combined$Cabin)]="Unknown"
combined$Cabin<-substr(combined$Cabin,1,1)
combined$Cabin<-as.factor(combined$Cabin)


p15<-combined%>%filter(dset=="train")%>%ggplot(aes(x=Cabin,fill=factor(Survived)))+geom_bar()+facet_grid(~Pclass)+
  labs(fill="Survived")


p16<-combined%>%filter(dset=="train")%>%group_by(Cabin,Pclass)%>%summarise(count=n(),SurvivalRate=mean(Survived))%>%
  ggplot(aes(y=SurvivalRate,x=Cabin))+geom_col()+facet_wrap(~Pclass)

grid.arrange(p15,p16,ncol=2,top="Survial by Cabin")


combined%>%filter(dset=="train")%>%group_by(Pclass,Sex,HasChildren)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  ggplot(aes(y=SurvivalRate,x=Pclass,fill=HasChildren))+geom_col(position="dodge")+facet_wrap(~Sex)

combined%>%filter(dset=="train")%>%group_by(Pclass,Sex,KnownSurvivor)%>%
  summarise(count=n(),SurvivalRate=mean(Survived))%>%
  ggplot(aes(y=SurvivalRate,x=Pclass,fill=KnownSurvivor))+geom_col(position="dodge")+facet_wrap(~Sex)

```

#Models
##Fitting Model
```{r Model,message=FALSE,warning=FALSE}

combined$Embarked<-as.factor(combined$Embarked)
combined$HasChildren<-as.factor(combined$HasChildren)
combined$KnownSurvivor<-as.factor(combined$KnownSurvivor)
combined$title<-as.factor(combined$title)
combined$PClassSex<-as.factor(combined$PClassSex)
combined$Survived<-as.factor(combined$Survived)
combined$Ticket<-as.factor(combined$Ticket)
combined$Ischild<-as.factor(combined$Ischild)
combined$FamilyID<-as.factor(combined$FamilyID)




train<-combined%>%filter(dset=="train")
test<-combined%>%filter(dset=="test")%>%mutate(Survived=1)

trainY<-train$Survived
levels(trainY)=c("N","Y")
myFolds<-createFolds(trainY,k=5)

## 5 Fold cross validation, twoclassSummary for AUC
myControl<-trainControl(
  summaryFunction = defaultSummary,
  classProbs = TRUE,
  savePredictions = TRUE,
  verboseIter = FALSE,
  index = myFolds,
  method = "cv"
)

names(getModelInfo())[1:5]


full=Survived ~ Pclass+Sex+Embarked+title+fsize+Fare+Age+KnownSurvivor+Parch+SibSp+FamilyID
sub=Survived~Pclass+Sex+TsizeCat+Age+KnownSurvivor+FarePP+title

##glmnet without title???
trainX<-model.matrix(full,data=train)[,-1]
trainX_subset<-model.matrix(sub,data=train)[,-1]
testX<-model.matrix(full,data=test)[,-1]
testX_subset<-model.matrix(sub,data=test)[,-1]



xgb_grid <- expand.grid(
  nrounds = c(10,300,350,400,500,600),
  eta = 0.01,
  max_depth =c(1,2,3,5,6,8),
  gamma = c(0,0.5,1,5,10),
  colsample_bytree=c(0.6,0.9),
  min_child_weight=c( 1, 1.5,2),
  subsample=c(0.6,0.8)
)

modelLookup(model='svmPoly')
#models[["mxnetAdam"]][["finalModel"]][["tuneValue"]]
#models[["svm_poly_sub"]][["bestTune"]]

params_list<-list(
  glmnet=list(method="glmnet",x=trainX,tuneGrid=expand.grid(alpha=1,lambda=0.03030304)),
  glmnet_sub=list(method="glmnet",x=trainX_subset,tuneGrid=expand.grid(alpha=1,lambda=1e-08)),
  ranger=list(method="ranger",x=trainX,importance="impurity",num.trees = 1000,
            tuneGrid=expand.grid(.mtry=18,.splitrule = c("gini"))),
  ranger_sub=list(method="ranger",x=trainX_subset,importance="impurity",num.trees = 1000,
                  tuneGrid=expand.grid(.mtry=6,.splitrule = c("extratrees"))),
  svm_linear=list(method="svmLinear",x=trainX,tuneGrid=expand.grid(C=1.000031),preProcess= c('center', 'scale')),
  svm_linear_sub=list(method="svmLinear",x=trainX_subset,tuneGrid=expand.grid(C=10.00003)),
  svm_poly=list(method="svmPoly",x=trainX,tuneGrid=expand.grid(C=2,degree=1,scale=0.1)),
  svm_poly_sub=list(method="svmPoly",x=trainX_subset,tuneGrid=expand.grid(C=4,degree=1,scale=0.1)),
  #mxnetAdam=list(method="mxnetAdam",x=trainX,tuneLength=5),
  #mxnetAdam_sub=list(method="mxnetAdam",x=trainX_subset,tuneLength=5),
  xgbTree=list(method="xgbTree",x=trainX,tuneGrid=expand.grid(
  nrounds = c(10),
  eta = 0.01,
  max_depth =c(3),
  gamma = c(0),
  colsample_bytree=c(0.9),
  min_child_weight=c( 1),
  subsample=c(0.6)
)),
  xgbTree_sub=list(method="xgbTree",x=trainX_subset,tuneGrid=
expand.grid(
  nrounds = c(300),
  eta = 0.01,
  max_depth =c(8),
  gamma = c(0),
  colsample_bytree=c(0.9),
  min_child_weight=c( 1.5),
  subsample=c(0.9)
)),
  cforest=list(method="cforest",x=trainX,tuneGrid=expand.grid(mtry=48)),
  cforest_sub=list(method="cforest",x=trainX_subset,tuneGrid=expand.grid(mtry=10))
)

#,preProcess= c('center', 'scale')
models<-invoke_map(caret::train,params_list,y=trainY,trControl=myControl,metric="Accuracy")
names(models)=names(params_list)
#plot(models[["xgbTree"]])
#plot(models[["xgbTree_sub"]])
#plot(varImp(models[["xgbTree_sub"]]))
#models[["mxnetAdam_sub"]][["finalModel"]][["tuneValue"]]


resamples<-resamples(models)
summary(resamples)
bwplot(resamples,metric="Accuracy")
```

##Prediction and Ensemble
```{r,message=FALSE,warning=FALSE}
dataset<-rep(list(testX,testX_subset),length(models)/2)
test_pred<-pmap(list(object=models,newdata=dataset),predict,type="prob")
pred_df<-bind_cols(test_pred)%>%select(contains("y"))
colnames(pred_df)<-names(models)

#cor(pred_df)
corrplot.mixed(cor(pred_df), order="hclust", tl.col="black")



pred_df$ensemble_avg<-(pred_df$svm_linear+pred_df$cforest+pred_df$svm_poly+pred_df$xgbTree)/4

##voting



ensemble_models<-caretList(y=trainY,x=trainX,trControl=myControl,
                           tuneList = list(
                          svmLinear=caretModelSpec(method="svmLinear",tuneGrid=expand.grid(C=1.000031)),
                          cforest=caretModelSpec(method="cforest",tuneGrid=expand.grid(mtry=48))
                           ))

stack <- caretStack(ensemble_models,method="glm",trControl=myControl)

pred_df$ensemble_stacked<-predict(stack,newdata=testX, type="prob")


#test_pred%>%names(.)%>%
#    walk(~write.csv(data.frame(PassengerId=test$PassengerId,Survived=ifelse(test_pred[[.]]["Y"]>0.5,1,0)),
#                   paste0(.,".csv"),row.names=FALSE)
#        )

pred_df%>%names(.)%>%
    walk(~write.csv(data.frame(PassengerId=test$PassengerId,Survived=ifelse(pred_df[,.]>0.5,1,0)),
                   paste0(.,".csv"),row.names=FALSE)
        )

saveRDS(models,"models.rds")



```
##Full tuning paramter List
```{r }
params_list<-list(
  glmnet=list(method="glmnet",x=trainX,tuneGrid=expand.grid(alpha=0:1,lambda=seq(1e-08, 1, length = 100))),
  glmnet_sub=list(method="glmnet",x=trainX_subset,tuneGrid=expand.grid(alpha=0:1,lambda=seq(1e-08, 1, length = 100))),
  ranger=list(method="ranger",x=trainX,importance="impurity",num.trees = 1000,
            tuneGrid=expand.grid(.mtry=seq(1,ncol(trainX),1),.splitrule = c("gini","extratrees"))),
  ranger_sub=list(method="ranger",x=trainX_subset,importance="impurity",num.trees = 1000,
                  tuneGrid=expand.grid(.mtry=seq(1,ncol(trainX_subset),1),.splitrule = c("gini","extratrees"))),
  svm_linear=list(method="svmLinear",x=trainX,tuneLength=30),
  svm_linear_sub=list(method="svmLinear",x=trainX_subset,tuneLength=30),
  svm_poly=list(method="svmPoly",x=trainX,tuneLength=5),
  svm_poly_sub=list(method="svmPoly",x=trainX_subset,tuneLength=5),
  mxnetAdam=list(method="mxnetAdam",x=trainX,tuneLength=15),
  mxnetAdam_sub=list(method="mxnetAdam",x=trainX_subset,tuneLength=15),
  xgbTree=list(method="xgbTree",x=trainX,tuneGrid=xgb_grid),
  xgbTree_sub=list(method="xgbTree",x=trainX_subset,tuneGrid=xgb_grid),
  cforest=list(method="cforest",x=trainX,tuneLength=15),
  cforest_sub=list(method="cforest",x=trainX_subset,tuneLength=15)
)
```
